project:
  type: website
  resources:
    - figs/
  render:
    - "*.qmd"
    - "!survey/"

pagetitle: "sdstudio GW OSCON"
title: "`sdstudio`<br>[A Companion Package for Designing<br>and Managing `surveydown` Surveys]{.small}"
author: "<br>**Pingfan Hu**<br>George Washington University<br><br>GW OSCON 2026"

format:
  touhou-revealjs:
    css: styles/slides.css
    smaller: false
    slide-number: true
    embed-resources: false
    auto-stretch: false
    footer: "<a href='http://pingfanhu.com'>Pingfan Hu</a> - <a href='https://ospo.gwu.edu/open-source-conference-2026'>GW OSCON 2026</a>"
    preview-links: auto
    link-external-newwindow: true
    link-external-icon: false
    center-title-slide: true
    code-block-height: 650px
    title-slide-attributes:
      class: custom-title-slide
      style: "text-align:left; background-image: url(figs/logo-sdstudio.png); background-size: 25%; background-position: right 7% center;"

execute:
  warning: false
  echo: false
