project:
  type: website
  output-dir: _site

pagetitle: "sdstudio GW OSCON"
title: "`sdstudio`<br>[A Companion Package for Designing<br>and Managing `surveydown` Surveys]{.small}"
author: "<br>**Pingfan Hu**<br>George Washington University<br><br>GW OSCON 2026"

format:
  revealjs:
    smaller: false
    theme: styles/slides.scss
    slide-number: true
    embed-resources: false
    auto-stretch: false
    footer: "<a href='http://pingfanhu.com'>Pingfan Hu</a> - <a href='https://ospo.gwu.edu/open-source-conference-gw-oscon'>GW OSCON 2026</a>"
    preview-links: auto
    link-external-newwindow: true
    link-external-icon: false
    center-title-slide: true
    code-block-height: 650px
    title-slide-attributes:
      data-background-image: figs/logo-sdstudio.png
      data-background-size: 18%
      data-background-opacity: "1"
      data-background-position: right 20% center
      class: custom-title-slide
      style: text-align:left; max-width:70%;

execute:
  warning: false
  echo: false
